### ISSUE TITLE
Cannot use plopp.scatter3d with matplotlib subplots

### ISSUE THREAD

**Issue by celinedurniak** [scipp/plopp#116]
Trying to use `plopp.scatter3d` with matplotlib subplots gives an error: "unexpected keyword argument 'ax'".

Here is a code example to reproduce the error

```
time = np.linspace(0, 10, 50)
x = np.cos(time)
y = np.sin(time)

da = sc.DataArray(
    data=sc.array(dims=['row'], values=time),
    coords={
        'x': sc.array(dims=['row'], unit='m', values=x),
        'y': sc.array(dims=['row'], unit='m', values=y),
        'time': sc.array(dims=['row'], unit='s', values=time)
    })

fig, ax = plt.subplots(1, 2, figsize=(10, 10))

p1 = pp.plot(da, ax=ax[0])
p2 = pp.scatter3d(da, x='x', y='y', z='time', pixel_size=0.2, ax=ax[1])

fig.tight_layout()
```

**Comment by nvaytet** [comment]
`scatter3d` does not use Matplotlib but Pythreejs, so you will not be able to embed a `scatter3d` plot inside a Matplotlib figure.
The only way to achieve something similar is to use widgets, as in the example here: https://scipp.github.io/plopp/customization/subplots.html#Using-container-widgets
It requires you to be using the `%matplotlib widget` backend in your notebook.

```Py
%matplotlib widget
import plopp as pp
...
p1 = pp.plot(da)
p2 = pp.scatter3d(da, x='x', y='y', z='time', pixel_size=0.2)

pp.widgets.Box([p1, p2])  # to have p1 above p2
```
or
```Py
pp.widgets.Box([[p1, p2]])  # to have p2 next to p1
```

**Comment by SimonHeybrock** [comment]
As more users may by trying this, could `scatter3d` detect the `ax` keyword and raise a meaningful error, referring, e.g., to an FAQ entry?
