### ISSUE TITLE
Wrong 1-D plots from mapping to items with distinct dimensions

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#122]
Example 1:
```python
import scipp as sc

x = sc.arange('x', 0, 5, 0.5)
y = sc.arange('y',0, 12,0.7)
dg = sc.Dataset({'a':x,'b':y})
dg.coords['x'] = x
dg.coords['y'] = y
dg.plot()
```
Creates a plot with "y" labeling the axis.

Example2:
```python
import scipp as sc

x = sc.arange('x', 0, 5, 0.5)
y = sc.arange('y',0, 12,0.7)
dg = sc.Dataset({'a':x,'b':y})
dg.plot()
```
Similar problem for items without coords.

**Comment by nvaytet** [comment]
We probably need to define a good set of rules. E.g.

If the dimension name and coordinate unit is the same, allow new line to be plotted.
If not, raise an exception?

Is that enough?
