### ISSUE TITLE
Using `plotly` as a backend instead of `matplotlib`

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#127]
After having spent a few days experimenting how to use Plotly for 1d and 2d figures instead of Matplotlib, I summarize my findings here, and delay any further work on this until it is a hard requirement.

## Things that went well

- This revealed all the places where Matplotlib-specific code was still present. We thought we had isolated it to a few files in the `graphics` folder, but it turned out it was in many more places. This is the part of the work that we will keep.
- Getting a 1d plot working was very easy, and things like updating errorbars was much easier in Plotly than in Matplotlib.
- It was easy to come up with a mechanism where switching back and forth between Matplotlib and Plotly was a simple `plopp.use('matplotlib')` and `plopp.use('plotly')`

## The main showstopper: 2d plots

After trying for a long time to get all the aspects of the 2d `Heatmap` to work for 2d plots, it was in the end not possible to implement a fully working solution.
The reasons were:

- We cannot make `Heatmap` with log colorbar (you have to pass the log of the values)
- We cannot change rgb colors of `Heatmap` patches directly, making it incompatible with the `Colormapper` mechanism we implemented for both Matplotlib meshes and Pythreejs point clouds (the `Colormapper` handles `vmin`, `vmax`, log normalization as well as grayscale masks)
- While we can set rgb values for a Plotly `Image`, we cannot use 'auto' aspect ratio scaling using `Image`, leading to very stretched images if e.g. the x axis spans a very different range from the y axis. We also cannot use `Image` if all pixels do not have the same size.
- tried using a layout (background) image, behind a transparent `Heatmap`, but the layout image does not play well with log axes (see https://community.plotly.com/t/is-it-possible-to-manually-set-the-rgb-colors-of-a-heatmap/70989/3)

For these reasons, I will not try to implement a Plotly backend at this stage.
I will however put all the Matplotlib code in a single folder, and make sure it is isolated as much as possible.

@arm61

**Comment by SimonHeybrock** [comment]
> For these reasons, I will not try to implement a Plotly backend at this stage.

I don't see this as a reason. I think it is perfectly valid if (for now, or even for a long time) a certain backend has limited features, such as not supporting 2-D plots. Wouldn't there be value in continuing this development until you have proper plotly support for 1-D plots? 2-d can always be added as future work.

**Comment by nvaytet** [comment]
ok, I can only support 1D plots for now. @arm61 would that still be of use to you?

**Comment by arm61** [comment]
With the current feature-set of EasyR, yes. But in future we might expand to more complex plots.
