### ISSUE TITLE
Figures for graph building blocks are not documented.

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#153]
https://scipp.github.io/plopp/examples/custom-interfaces.html references, e.g., `plopp.figure1d`, to use as building block in graphs. However, this appears to be undocumented, i.e., I cannot find it in the class/function reference docs.

**Comment by nvaytet** [comment]
They do appear in the latest `main` docs, but there are no docstrings. So this does indeed need fixing.
![Screenshot at 2023-02-08 09-35-17](https://user-images.githubusercontent.com/39047984/217477300-42c2240f-2e6f-4418-8b5d-ffeebc73e711.png)

Also, not sure what's going on with the backends, but there doesn't seem to be much there.
