### ISSUE TITLE
2-D plot given multiple inputs puts one image on top of the other, hiding the one below

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#162]
```python
import scipp as sc
import plopp as pp

var1 = sc.ones(dims=['x', 'y'], shape=[200,300])
var2 = var1 * 100

pp.plot({'a':var1, 'b':var2})
```
plots `var2`. I guess it should raise instead?

**Comment by nvaytet** [comment]
`var1` is also plotted, it's just that they are occupying the same area, and `var2` is drawn after `var1`.
If you offset the coordinates of one of them
```Py
import scipp as sc
import plopp as pp

var1 = sc.ones(dims=['x', 'y'], shape=[200,300])
var2 = var1 * 100
da1 = sc.DataArray(data=var1, coords={'y': sc.arange('y', 300)})
da2 = sc.DataArray(data=var2, coords={'y': sc.linspace('y', 310, 410, 300) })

pp.plot({'a':da1, 'b':da2})
```
you get
![Screenshot at 2023-02-20 08-03-44](https://user-images.githubusercontent.com/39047984/220035824-a9dd9bde-4edc-4b34-883e-ef87464d1fbd.png)

Now what's weird is that the label next to the colorbar says `a [dimensionless]`.
I guess it was trying to emulate the legend in 1d figures, but we should probably have nothing there.
