### ISSUE TITLE
show function

### ISSUE THREAD

**Issue by jl-wynen** [scipp/plopp#165]
As in MPL, it would be good to have `plopp.show` which opens windows for current figures and starts an event loop. This way, a user can use this feature independent of the current backend. (Provided all backends actually support this...)

**Comment by nvaytet** [comment]
So in `ipython` (in the terminal), you can do
```Py
p = pp.plot(da)
p.canvas.show()
```
(if using mpl backend). Does that solve part of your problem?

This doesn't currently work in jupyter, it says
```
UserWarning: Matplotlib is currently using module://matplotlib_inline.backend_inline, which is a non-GUI backend, so cannot show the figure.
```

What did you mean exactly by "opens windows for current figures"?
This would open 5 windows if you have created 5 figures so far?

**Comment by jl-wynen** [comment]
> What did you mean exactly by "opens windows for current figures"?
  This would open 5 windows if you have created 5 figures so far?

This is what `plt.show()` does, right?

> Does that solve part of your problem?

For well written code, probably. But for a quick and dirty, call `pp.plot` and at the end of the script, show everything approach, a free function would be best.

And I don't expect this to work in Jupyter. This is only meant for scripts.

**Comment by nvaytet** [comment]
> This is what plt.show() does, right?
:+1: 

Since `plotly` and `pythreejs` plots can only work in Jupyter, this can only apply to the matplotlib backend for now.
But it should be easy enough to add a `show()` method.

**Comment by nvaytet** [comment]
Note that using `p.canvas.show()` is not exactly the same, as it will not start an event loop and in a scripts, the plots will just be shown for a fraction of a second and then disappear.
