### ISSUE TITLE
Cropped tick values of colobar of plopp.slicer

### ISSUE THREAD

**Issue by celinedurniak** [scipp/plopp#176]
The tick values of the colorbar can sometimes be cropped.
Widening the figure (by dragging the little grey triangle at the lower right hand side of the figure) does not help because it also stretched the graph.
See below the code that can be used to reproduce the issue. Please note that cropped values appear for the largest values along the slider.

```
import pandas as pd
import scipp as sc
import plopp as pp

%matplotlib widget

filename = 'https://public.esss.dk/groups/scipp/scipp/1/data_dream_diamond.zip'
df = pd.read_table(filename)
ds = sc.compat.from_pandas(df)

del ds.coords['row']  # we have no use for this row index
for key in list(ds):
    name, *remainder = key.split(' ')
    ds[name] = ds.pop(key)
    ds[name].unit = remainder[0][1:-1] if remainder else None

table = sc.DataArray(sc.ones(sizes=ds.sizes, unit='counts'))
for name in ds:
    table.coords[name] = ds[name].data

radius = sc.sqrt(table.coords['x_pos'] ** 2 + table.coords['y_pos'] ** 2)
table.coords['radius'] = radius
binned_radius_z_tof = table.bin(z_pos=100, radius=100, tof=100)

pp.slicer(1000*binned_radius_z_tof.hist(), keep=['radius', 'z_pos'], grid=True)
```

**Comment by nvaytet** [comment]
> Please note that cropped values appear for the largest values along the slider.

I think that is the key here. Matplotlib won't automatically re-apply a `tight_layout()` when the values along the colorscale are modified. I tired adding a call to `tight_layout()` every time the figure is updated, and while that fixes the cropping issue, it also resizes the image so that it fits in the current viewable area. Basically, it means the figure appears to 'jump' when you move to the next power of 10 in values.

I don't know if I prefer the cropping or the jumping...

**Comment by SimonHeybrock** [comment]
Can we either apply some extra padding by default, or use scientific notation so width stays consistent?

**Comment by nvaytet** [comment]
Could work, now I just have to figure out how to make matplotlib behave like that ;-)

**Comment by nvaytet** [comment]
@celinedurniak can you check if this is still an issue?

On latest `main`, I tried
```Py
import plopp as pp

%matplotlib widget

da = pp.data.data3d() * 1.0e6
pp.slicer(da)
```
and the ticklabels on the colorbar look ok?
![Screenshot at 2024-09-13 17-34-01](https://github.com/user-attachments/assets/e6eae6de-2e5f-4a9c-b50f-ac7e36de432a)

**Comment by celinedurniak** [comment]
@nvaytet The example you used works for me too. But I tried with the code at the top of the page and the ticks are still cropped (see screenshot below)

<img width="543" alt="Screenshot 2024-09-13 at 19 47 35" src="https://github.com/user-attachments/assets/ed3e2b44-ea5d-4815-8235-09763b0df2dc">

**Comment by nvaytet** [comment]
Thanks for checking.
I don't really know how to reproduce. I tried to make a figure closer to what you have (values and axes labels), but still no cropped tick labels :-( 

```Py
da = pp.data.data3d()**2 * 2.8e5
da.coords['y'] -= sc.scalar(20., unit='m')
da.coords['y'] *= 1.0e2
da = da.rename(y='z_pos')
da.unit = 'counts'
pp.slicer(da)
```
![Screenshot at 2024-09-16 08-33-02](https://github.com/user-attachments/assets/4c3e92aa-9fbb-47b4-8a3a-f014ff02cd02)

**Comment by celinedurniak** [comment]
@nvaytet FYI I found out that I could rescale the figure by moving the grey triangle (bottom right corner) to get the complete ticks displayed.

**Comment by nvaytet** [comment]
If that's an ok workaround for you, are you happy to close this issue?
You can reopen if you meet this issue in a different use case?

**Comment by celinedurniak** [comment]
You can close this issue. Thanks.
