### ISSUE TITLE
Behaviour of autoscaling colorbar

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#178]
Until now, the limits on the colorbar of a 2d plot are allowed to grow with time, but not shrink.
This means that if a figure receives new data, e.g. a new slice selected from moving a slider, if the range of new values is wider than the current range, the limits on the colorbar will autoscale to the new data.
If the range is smaller, the colorscale will not change.

This was intentional to give a better feel for the relative intensities of the different slices, while at the same time allowing the user to see new features as they appear.

However, this does have the strange effect that if a user is navigating through a 3d data set, sees a feature (some peaks), continues through the data, and then wants to come back to the peaks, the colorscale may now be different and the peaks could have been washed out if a higher range was displayed when the slider when past the peaks.

The two alternatives are:
1. Use the whole range of the 3d data as the limits, and keep them constant. This may mean that the user never sees those small peaks in the first place, but it has the advantage of moving the slider back to a previous location will always show the same image
2. Always autoscale on the displayed slice. This may be what the user expects the most, and would also show the same image when going back to a previous slider position. But the entire custom mechanism was designed to provide a better feel for the data.

A third option could be to keep the current mechanism, but then use the `Home` button to both autoscale the axes and the colorscale. Currently the `Home` button just goes back to the currently set limits, which may be wider than the displayed data, if the slider previously took you to a region where the range of values was wider.

@celinedurniak

**Comment by nvaytet** [comment]
Another possibility would be to be able to double-click the colorbar to apply a manual rescale. But the behaviour needs to be consistent between the y axis of a 1d plot and the colorscale of a 2d plots, and double-clicking on an axis is not good.

**Comment by SimonHeybrock** [comment]
Can we provide a keyword argument to select the behavior (between the 3 or so options)?

**Comment by SimonHeybrock** [comment]
> However, implementing option 1 would only be possible (without major changes) for the slicer plot, and not for the lower level figure2d. But I guess that would cover something like 80-90% of the use cases?

You mean in case someone makes a custom graph?

> We also need to decide which should be the default behaviour... I would vote to keep the current behaviour as the default, but maybe users expect option 2 instead?

Personally I feel using the full range by default is most sensible and least surprising.

**Comment by nvaytet** [comment]
> You mean in case someone makes a custom graph?

yes

**Comment by SimonHeybrock** [comment]
> > Personally I feel using the full range by default is most sensible and least surprising.
> 
> But we didn't do that because people would see nothing in their first e.g. 100 slices because in slice 200 there is a hot pixel, or something...

Then they can change the default. I thought it to be more dangerous to auto-scale the color-bar, making people wrongly believe all their data is constant, for example.

**Comment by nvaytet** [comment]
> dangerous to auto-scale the color-bar, making people wrongly believe all their data is constant

yes, that's what I didn't like about autoscaling on every slice, where only the numbers along the colorbar are changing instead of the colors

**Comment by celinedurniak** [comment]
FYI I recently used `plopp.slicer` to scroll through temporal frames of a faulty 2D detector, which would randomly (in space and time) record high intensity pixels. The default behavior of the intensity scaling made that, for example, going back to the first image after having checked all the frames did not display the same as when initially loaded.
