### ISSUE TITLE
Adding operators to plots?

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#180]
Some projects like Holoviz have added operators to plots (see e.g. [here](https://holoviz.org/tutorial/Composing_Plots.html)).
For example, they use the `*` operators between two plots to overplot the data from both onto the same axes.
They use the `+` operator to make tiled plots.

Do we want to add something similar?
While I am not sure about the usefulness of the `*` operator (and also not sure whether it is a good choice), maybe some aspects are interesting? Making tiled plots with `p1 + p2` is definitely appealing, instead of having to always use the `Box([p1, p2])`.
I don't know how you would make horizontal and vertical tiles. Maybe the `/` operator could be used to make one plot above the other.
So something with 4 panels would be `(p1 + p2) / (p3 + p4)`.

I think having operators would definitely be beneficial for cropping (setting the axes limits).
Right now, to set the axis limits, one needs to use a rather strange syntax to set the limits for the `time` dimension:
`da.plot(crop={'time': {'min': 2.5, 'max': 40.}})`
It would be nice if instead we could use the same slicing syntax as we have on sc.DataArray to crop:
`da.plot()['time', 2.5:40.]`.

Note however that using integers may become confusing, as `da.plot()['time', 2:40]` would be cropping on the values of the `time` coordinate, not slicing using integer indices.

**Comment by nvaytet** [comment]
Tagging a few people to start a discussion: @celinedurniak @SimonHeybrock @jl-wynen @YooSunYoung @wpotrzebowski @arm61 @g5t

**Comment by YooSunYoung** [comment]
>I think having operators would definitely be beneficial for cropping (setting the axes limits).
Right now, to set the axis limits, one needs to use a rather strange syntax to set the limits for the time dimension:
da.plot(crop={'time': {'min': 2.5, 'max': 40.}})
It would be nice if instead we could use the same slicing syntax as we have on sc.DataArray to crop:
da.plot()['time', 2.5:40.].

What will be the difference between `da['time', 2.5:40.0].plot()` and `da.plot()['time', 2.5:40.0]`?

**Comment by nvaytet** [comment]
So `da['time', 2.5:40.0].plot()` is actually not allowed with Scipp, you have to do `da['time', sc.scalar(2.5, unit='s'):sc.scalar(40.0, unit='s')].plot()`.
And I now think that we should not allow `da.plot()['time', 2.5:40.0]`, but only allow `da.plot()['time', sc.scalar(2.5, unit='s'):sc.scalar(40.0, unit='s')]`.
Basically, I thought about allowing it because we allow values for `vmin` and `vmax` (e.g. setting the vertical limits on a 1d plot) to not have units (for convenience). It's fine there because it's pretty unambiguous: if the y values have a unit, you just assume the same units for `vmin` and `vmax`.
But in the example given above, I think it would be weird to have a syntax which is not allowed in Scipp itself.

Now to answer your question about what would be the difference between `da['time', sc.scalar(2.5, unit='s'):sc.scalar(40.0, unit='s')].plot()` and `da.plot()['time', sc.scalar(2.5, unit='s'):sc.scalar(40.0, unit='s')]`, when you slice the data first and plot afterwards, you get the data between 2.5 and 40s, but then in the case of a 1d plot, some whitespace is added around the data points so as to not have points right on the edge of the graph.

I was thinking that slicing after plotting could set the exact requested limits on the axes, trimming the whitespace. It would be like doing `ax.set_xlim(2.5, 40)` in Matplotlib.

In the case of 2d data, if your data has bin edges, slicing before plotting always selects full bins, so even if you ask for 2.5, the lower bound for the data might be 2 if 2.5 falls in the middle of a bin. Therefore, your displayed figure would start at 2, not 2.5. Once again, slicing after plotting could set the lower limit exactly to 2.

Finally, because there are many questions associated to cropping (see #182), I am thinking of not necessarily adding the `getitem` operator just now, but we could start with the `+` and `/` for making tiled plots and see how that goes?

**Comment by g5t** [comment]
:+1: for not introducing another syntax different from `scipp` `scalar` range slicing. It's verbose but precise.

**Comment by nvaytet** [comment]
> +1 for not introducing another syntax different from `scipp` `scalar` range slicing. It's verbose but precise.

See also https://github.com/scipp/scipp/issues/3087

**Comment by SimonHeybrock** [comment]
Personally I think the `+` and `/` notation is a bit misleading and not very intuitive. How much would really be gained from this? Is there a more clear (if slightly more verbose) alternative?

**Comment by YooSunYoung** [comment]
> Personally I think the + and / notation is a bit misleading and not very intuitive. How much would really be gained from this? Is there a more clear (if slightly more verbose) alternative?

I think `+` and `/` sounds very useful and it is intuitive for simple cases.

But I would prefer having a grid and assign the plot into the cells if I want to make a slightly complicated multi-plots view like other plotting libraries.
Sth like... 

```
pp.grid((2, 3))
pp.plot(da, cell=(1, 2))
```

**Comment by SimonHeybrock** [comment]
How about:

```
tiled = pp.tiled(3,2)
tiled[0, 0] = pp.plot(...)
tiled[0, 1] = pp.plot(...)
...
```

**Comment by nvaytet** [comment]
Note that we already have the `Box` to make subplots, but that only works with the widget backend.
I guess we would want the new mechanism to work with any backend?
Finally, would `tiled` also support range slicing, e.g. `tiled[0:2, 1] = plot`, a bit like matplotlib's gridspec?

**Comment by nvaytet** [comment]
So I came across this again, while in a notebook and wanting to quickly put two plots side by side.
I do actually feel like being able to do
```Py
da1.plot() + da2.plot()
```
is quite neat and way more concise than
```Py
tiled = pp.tiled(1, 2)  # I can never remember if it's (1, 2) or (2, 1) here in MPL
tiled[0] = da1.plot()
tiled[1] = da2.plot()
tiled
```

What I am saying is that one does not have to exclude the other. We could have the `tiled` for better control over which figure covers which parts of the tiled space (like the range slicing I mention above), but for quick results, having operators `+` and `/` (for vertical stacking) could be really useful?
