### ISSUE TITLE
Docs build issue on GH actions with finding git repo

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#196]
See https://github.com/scipp/plopp/actions/runs/4668036986/jobs/8264570697#step:7:150

It seems the repo is not found (wrong path?), but the build still succeeds and the uploaded online docs look ok.

**Comment by nvaytet** [comment]
While the latest docs look ok, the docs from the previous releases are absent.

**Comment by SimonHeybrock** [comment]
I think the changes to `version.py` made it work only from a certain directory (iirc)... let me find how I fixed it in scipp.

**Comment by nvaytet** [comment]
Fixed in #198
