### ISSUE TITLE
Add legend control

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#206]
We need options in the `plot` function to hide the legend and control its placement.
Would be something like
```Py
pp.plot(dict, legend=False)
pp.plot(dict, legend=(0.1, 0.9))
```
The latter would control the location, see the `loc` parameter in https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html.

**Comment by YooSunYoung** [comment]
Will it also mean that we can place the legend outside of the plot easily?

**Comment by nvaytet** [comment]
> Will it also mean that we can place the legend outside of the plot easily?

Yes, the values in the `loc` parameter can be greater than 1.
