### ISSUE TITLE
Remove the Plotly backend?

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#236]
The Plotly backend was introduced in #128 mainly as an experimental feature.
It was also instrumental in properly containing the other backends used (matplotlib, pythreejs).

However, it has remained undocumented to this date, and also very much unused.

There are several things that are currently not working with the backend:

- making 2D image plots (see #222)
- making tiled plots (see #223)
- legend positioning

and probably many others.

Getting these things to work represents a non-negligible amount of work.
In addition, it has come with a significant maintenance overhead, when adding new features or changing existing ones, as we have to often propagate changes across two backends.

Considering the fact that no users are currently using it, and that it is not documented anywhere, should we simply remove it?

**Comment by jl-wynen** [comment]
Keeping this backend helps to maintain the encapsulation of the backend. So if you remove it now, there is a risk that new features and refactors increase the coupling to matplotlib and make it harder to support other backends in the future.
How do you see this risk?

**Comment by SimonHeybrock** [comment]
I think I agree: Either make a decision "we will never support anything but Matplotlib", or keep it.

**Comment by nvaytet** [comment]
So is the idea that we keep it but never add any new features to it as long as no one asks for them?
