### ISSUE TITLE
Plotting data with `vector3` dtype plots components

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#240]
This was unexpected:

```python
import scipp as sc

sc.vectors(dims=['vec'], values=[[1,2,3],[4,5,6]], unit='m').plot()
```
<img width="509" alt="image" src="https://github.com/scipp/plopp/assets/12912489/051f4ee2-8af5-4abc-9352-211164bad73a">

I would have expected an error.

**Comment by nvaytet** [comment]
Hmmm, apparently that is just matplotlib now that makes multiple lines when given a 2d input
![Screenshot at 2023-09-12 09-43-57](https://github.com/scipp/plopp/assets/39047984/ee5f7b36-4a0b-430d-a0c6-7cfe4c0e8000)

I probably need to verify the type on input.
