### ISSUE TITLE
Axis mislabeled with 2-D coord that is "transposed"

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#246]
Example:
```python
import scipp as sc
import plopp as pp

a = sc.linspace('a', 0,1,10, unit='m')
b = sc.linspace('b', 0,2,5, unit='s')

da = sc.DataArray(a*b, coords={'a':a, 'b':b*a})
da.plot()
```
Yields
<img width="536" alt="image" src="https://github.com/scipp/plopp/assets/12912489/c4c82432-7dab-4323-9799-af4805d786e7">

Note that the unit is correct, but apparently Plopp uses the name of the inner dim of a coord to get the axis name.

**Comment by nvaytet** [comment]
So you are saying that if you do `da = sc.DataArray(a*b, coords={'a':a, 'b':a*b})` instead, then the axis label is ok?

**Comment by SimonHeybrock** [comment]
Yes.
