### ISSUE TITLE
Allow other ways of handling masks?

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#266]
Currently, input data that contains masks will still see the masked values plotted on figure.
Masked values are distinguished from other values by either adding a black edge color around the point markers (1d plots), or by using a different colormap (2d plots).

However, sometimes a user really does not want to see the masked values, for example if the masked values are orders of magnitude larger than the part of the data they were interested in.

Example:
```Py
da = pp.data.data1d()
da.values[0] = 1000.
da.masks['large'] = da.data > sc.scalar(1.0, unit=da.unit)
pp.plot(da)
```
![Figure 17](https://github.com/scipp/plopp/assets/39047984/643d16a0-211e-4b20-a85d-6afe60b59fbc)

The fluctuations in the data cannot be seen because of the spike in the first data point, making the plot rather useless.

Maybe we can simply have an option, e.g. `drop_masked=True` to remove those points?
The question now is: should the default be `drop_masked=True` or `drop_masked=False`?

(Matplotlib has `drop_masked=True` by default for numpy masked arrays).

**Comment by jl-wynen** [comment]
How would this work with histograms and 2d plots?

**Comment by nvaytet** [comment]
I guess for histograms you would have gaps in the step curve (this also happens in raw matplotlib when you have NaNs in the data).
For 2d plots you would also have (white) gaps in the image?

Consider the difference with a hot pixel on a 2d image between our current plotting (top) and matplotlib (bottom)
![Screenshot at 2023-09-27 09-40-18](https://github.com/scipp/plopp/assets/39047984/e8051343-c045-4422-b60c-cbae5020927d)

**Comment by wpotrzebowski** [comment]
I would argue that for the instrument view, we should still keep masking by default and have an option to switch on and off. 
For 1D and 2D plots it is a reasonable proposal but it may be useful to throw a warning if the mask is omitted by default.

**Comment by nvaytet** [comment]
> we should still keep masking by default and have an option to switch on and off.

I don't think the question was about turning masks on or off, it was about how to represent the masks, and whether the masked values should be taken into account when computing limits (vertical axis for 1d plots, and colorbar for 2d plots).

**Comment by jokasimr** [comment]
It would be useful to have the option to drop the masked values. Since we currently display masked values by default perhaps it makes most sense to keep that as the default now and only add an option to drop? Perhaps we can add an option to change the default through some global setting.
