### ISSUE TITLE
Conda package depends on scipp

### ISSUE THREAD

**Issue by jl-wynen** [scipp/plopp#302]
We did not want the packages to depends on scipp so that we can use plopp in dev builds of scipp. But since plopp 23.11, the conda package does seem to depend on scipp. I don't know where this comes from, though, because scipp is not listed as a run dependency in `meta.yaml`. Maybe something happens with the test dependency.

**Comment by nvaytet** [comment]
I think Scipp is listed as a run dependency?

https://github.com/scipp/plopp/blob/main/conda/meta.yaml#L19

**Comment by jl-wynen** [comment]
Hm, I used git blame and it showed this as `run_constrained`. So was this accidentally moved into `run`?

**Comment by nvaytet** [comment]
Seems it used to be as `run_constrained`...
![Screenshot at 2024-01-30 16-32-41](https://github.com/scipp/plopp/assets/39047984/2df818bc-bbf9-448f-a0af-c4ee2ffa66c9)

Maybe when we switched to the copier template?

**Comment by nvaytet** [comment]
Indeed: https://github.com/scipp/plopp/pull/281/files#diff-e4db5852c039b631ee11f2e6f3b000f53e0774918ff1ba8f983f428f72b4fe4c
