### ISSUE TITLE
Fix Plopp unpinned tests

### ISSUE THREAD

**Issue by jokasimr** [scipp/plopp#308]
See https://github.com/scipp/plopp/actions/workflows/unpinned.yml.

**Comment by nvaytet** [comment]
I think this was fixed in #297 but we just have not made a release since?

**Comment by jokasimr** [comment]
Yeah that makes sense. Should we close this then?

**Comment by nvaytet** [comment]
I'll close and we can re-open if it's still failing after we make a release.
