### ISSUE TITLE
Cursor hover is broken on image with datetime coord

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#310]
To reproduce:
```Py
import plopp as pp
import numpy as np
import scipp as sc
%matplotlib widget

t = np.arange(
    np.datetime64('2017-03-16T20:58:17'), np.datetime64('2017-03-16T21:15:17'), 20
)
time = sc.array(dims=['time'], values=t)
z = sc.arange('z', 50.0, unit='m')
v = np.random.random(z.shape + time.shape)
da = sc.DataArray(
    data=sc.array(dims=['z', 'time'], values=10 * v, variances=v),
    coords={'time': time, 'z': z},
)
pp.plot(da)
```

Then, hovering the mouse cursor over the image raises:
```
File ~/code/plopp/jupyter/plopp/backends/matplotlib/image.py:228, in Image.format_coord(self, x, y)
    220 try:
    221     val = self._data_with_bin_edges[
    222         self._hover_slicing['dim'][0],
    223         sc.scalar(
   (...)
    226         ),
    227     ]
--> 228     val = val[
    229         self._hover_slicing['dim'][1],
    230         sc.scalar(
    231             xy[self._hover_slicing['dir'][1]],
    232             unit=self._hover_slicing['unit'][1],
    233         ),
    234     ]
    235     prefix = self._data.name
    236     if prefix:

DTypeError: 'less_equal' does not support dtypes 'datetime64', 'float64', 
```
(set log level to Debug in log console to see the error).

It also means that when trying to zoom, no zoom rectangle is drawn.

**Comment by nvaytet** [comment]
Even if we prevent the error above from occuring, the formatting is not great because the x, y values given by the cursor hover are floats (apparently converted using `matplotlib.dates.date2num`, and look very unrelated to the values on the datetime axis.

So I suggest, for now, to simply disable our custom hover formatter for figures (1d and 2d) where there is a datetime axis. The default matplotlib formatter will give the correct datetime hover value.

**Comment by jl-wynen** [comment]
Do you know how mpl solves this?

**Comment by nvaytet** [comment]
Maybe it knows that the axis is datetime and does the reverse conversion?
A `num2date` function also exists. However, it does return a full date.
Matplotlib probably then applies some special formatting (same as for the axes tick labels) to not show the full date.
However, maybe showing the full date could be useful?

**Comment by nvaytet** [comment]
> Do you know how mpl solves this?

Thanks for asking the question. I found a way to fix it, instead of disabling it :+1:
