### ISSUE TITLE
Logo is not rendered properly

### ISSUE THREAD

**Issue by jl-wynen** [scipp/plopp#32]
![logo-rendering](https://user-images.githubusercontent.com/11393224/192973099-59274e46-8bbb-40a7-984a-0b256491b8c2.png)

Also in README

Probably the same issue we had in scipp. I don't have the font. Can be fixed by converting the text to a path.

**Comment by SimonHeybrock** [comment]
Instructions are here: https://scipp.github.io/reference/developer/releasing-scipp.html#updating-the-logo
