### ISSUE TITLE
Zoom resets when using slicer

### ISSUE THREAD

**Issue by henrikjacobsenfys** [scipp/plopp#340]
If I have zoomed in to a particular range in my data, I'd usually like to keep that zoom level when using the sliders in the slicer. However, it resets the window.

**Comment by nvaytet** [comment]
I can either do a quick, simple a unexpensive fix, which would be to add an option to disable the autoscaling, with e.g.
```Py
pp.slicer(da, autoscale=False)
```
but that would disable both autoscaling the axes and the colorbar range.

Or I could implement a more complicated fix which would need to check whether the current limits were set by the data or by a zoom, and only autoscale in the former case.

So the question is would the simple fix be enough for your use case?

**Comment by henrikjacobsenfys** [comment]
I think the simple fix should be enough. I can't promise that I won't come back later and ask for a more complicated solution, but let's start with the simplest solution. Thanks!
