### ISSUE TITLE
Plot data update mechanism glitches

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#358]
I see this problem in both VScode and JupyterLab:

<img width="607" alt="image" src="https://github.com/user-attachments/assets/29be1579-0c59-4a1d-b0a5-b76f3f27537e">

I am trying to update the data using
```python
    fig.update({artist: mon.hist(wavelength=wav)})
    fig.fig.canvas.draw()
    fig.fig.canvas.flush_events()
```

**Comment by SimonHeybrock** [comment]
It works fine when using the `Node` mechanism. Do we even need the manual mechanism?

**Comment by nvaytet** [comment]
> Do we even need the manual mechanism?

Hopefully we can always use the node mechanism. The manual should be avoided where possible.
I think I sometimes still see glitches if a plot is continuously updating and I am using a pan or zoom tool, but not consistently reproducible.

Finally, if we start to make many interactive tools, we may want to move away from matplotlib and consider one of the javascript libraries like `plotly` or `bokeh`...
