### ISSUE TITLE
coord arg accepts multiple coords for same dimension

### ISSUE THREAD

**Issue by jl-wynen** [scipp/plopp#360]
The `coords` argument accepts multiple coords for the same dimension and uses the last one in the list:
![Screenshot_20240904_100350](https://github.com/user-attachments/assets/4b6e2366-8b18-471f-aa7e-8f1ed301d46e)

This is surprising to me. Should it instead raise an error?

**Comment by nvaytet** [comment]
> Should it instead raise an error?

Yes, I think so.
