### ISSUE TITLE
Polar projection in inspector plot

### ISSUE THREAD

**Issue by pordyna** [scipp/plopp#365]
Hi!
I really like your inspector plot and I would like to use it to visualize some histograms where the 2 remaining coordinates are polar coordinates. Is there any way to set the first axis in the plot (the one showing 2D data) to use the polar projection? I can't figure it out.

**Comment by pordyna** [comment]
Thanks, for answering so quick. Hmm, this somehow did not work for me before. I will try it out again with your snippet, though.

**Comment by nvaytet** [comment]
I also noticed that in the gallery example on polar plots, I make use of `plt.Figure` instead of the lowercase `plt.figure`.
The former seems to result in making a static image instead of an interactive figure.
This may be the thing that wasn't working? (I need to fix the docs)

Did you get a figure where nothing was happening or did you get an error?

**Comment by pordyna** [comment]
So for your dataset it kinda works, but I get the main figure twice and the colorbar is added only to the extra figure.
![image](https://github.com/user-attachments/assets/7caf5a21-b646-4dc2-89d9-8f94ddf4a1ba)

**Comment by nvaytet** [comment]
I probably used `plt.ioff()` in my notebook to prevent the figure from showing up twice...

**Comment by nvaytet** [comment]
To summarize, including the changes in #367 :
```Py
import numpy as np
import scipp as sc
import plopp as pp
import matplotlib.pyplot as plt
%matplotlib widget
plt.ioff()

da = pp.data.data3d(binedges=True, unit='K')
da.coords['x'] = sc.linspace('x', 0, 2 * np.pi, da.sizes['x'] + 1, unit='rad')

fig = plt.figure()
ax = fig.add_subplot(projection='polar')
pp.inspector(da, dim='z', ax=ax)
```
![Screenshot at 2024-09-11 10-21-10](https://github.com/user-attachments/assets/97a7c621-4ebe-46ac-84b4-d98e1d7ead60)

**Comment by nvaytet** [comment]
Closing as I think this is ok now? Feel free to re-open if I am mistaken :-)

**Comment by pordyna** [comment]
Looks good to me, thanks!
