### ISSUE TITLE
Consider allowing to specify limits such as vmin/vmax using float instead of Variable

### ISSUE THREAD

**Issue by nvaytet** [scipp/plopp#67]
For correctness, we decided in the past that in order to specify limits for a plot (such as `vmin/vmax`), the values needed to be variables with units.
This added an additional check that we were supplying the correct limits for the correct axis (it raised in case of a unit mismatch).

However, I feel that in practise, this is getting in the way of usability.
Users (including myself) find themselves writing
```Py
pp.plot(da, vmax=100)
```
and then quickly having to correct to
```Py
pp.plot(da, vmax=sc.scalar(100, unit='K'))
```
which is also quite verbose.

The verbose version could be useful in the case where we perform on-the-fly conversions, so one could specify a `vmin` in `cm` on an axis that was displaying meters, but we are not actually doing this in practise. We are simply raising an error in the case where the units don't match.

So the unit check is not really doing much, apart from getting in the way of rapid modification of plots, making quick iterations and epxloration of data in notebooks less fluid.
I don't think the unit check is that important, because it's obvious that the user meant "100 in the same unit as whatever is on the axis".

So I would be in favour of removing support for Variables and input, and just supporting floats. Or, supporting both, and in the case of Variable input, support on-the-fly conversion to whatever is on the axis.

**Comment by arm61** [comment]
I like this idea. **If** a float is given assuming the user is using the axis units is a good idea but also keep a Variable as an option (incase one wants to given the limits in a different unit). The verbosity isn't really required here as limits on a plot aren't really going to lead to mistakes in a reduction workflow.
