### ISSUE TITLE
Data size limits and SVG output

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#78]
Consider
```python
import scipp as sc
import plopp

data = sc.ones(dims=['x'], shape=[240_000])
sc.plot(data)
plopp.plot(data)
```
Scipp plots reasonably quickly, but the Plopp plot takes much longer to show, and even creates lag in the notebook after creation. I think the plotting itself is not the culprit, but the actual display in the notebook.

We could reduce the limit until which we can plot, but since it may "just" be a problem with the SVG output, we may consider switching to PNG for large data, or at least provide an option/recommendation?

**Comment by nvaytet** [comment]
Yes, good point. I will try a switch to png.
