### ISSUE TITLE
Text entry for plot sliders

### ISSUE THREAD

**Issue by jl-wynen** [scipp/plopp#88]
It is difficult to adjust sliders to fine tune parameters like the opacity in slice views. Here the difference between 0.03 and 0.02 matters and you have to be very precise with the mouse to adjust that. It would be helpful to be able to enter text in the label of the slider to enter a value directly.

**Comment by nvaytet** [comment]
> Snap to the nearest int?

I think this would also be annoying for users if they want to get exactly 33.78 and the slider just gives them 34 for no apparent reason?

**Comment by nvaytet** [comment]
Closing as inactive. Re-open if needed.
