### ISSUE TITLE
Log axes show too few decimal places or should use scientific notation

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/plopp#90]
Probably an issue with matplotlib's default that needs to be circumvented somehow? As it is now we just get `0.000` for some axis tics, here Y:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/12912489/105134320-867d3180-5aee-11eb-83fe-64bda539b9c9.png">

**Comment by nvaytet** [comment]
@SimonHeybrock  is this still an issue? The plot above may have been using an old version of Matplotlib.
Doing
```Py
import plopp as pp
import numpy as np

a = np.array([0.1, 100.0, 1.0e6])
pp.plot(a, norm='log')
```
today yields
![Screenshot at 2022-12-06 15-02-21](https://user-images.githubusercontent.com/39047984/205932588-b273cf97-cebe-4a04-9235-89d046d7049c.png)

**Comment by nvaytet** [comment]
Or maybe it was due to the mess we had when dealing with the axis tick formatters?

**Comment by nvaytet** [comment]
I also checked on a 2d plot, seems to work ok
![Screenshot at 2022-12-06 15-10-52](https://user-images.githubusercontent.com/39047984/205934500-fe40e15e-e01b-4a54-a61b-644e96931351.png)

**Comment by nvaytet** [comment]
I think if you have bin centers for the vertical coordinate, and you put it on a log scale, the bottom edge of the first pixel will be negative (just like you see -0.5 on the horizontal axis) and it will struggle to find a good lower bound for the vertical dimension. If you use bin edges, it should work better?

**Comment by SimonHeybrock** [comment]
Probably. Anyway, I think this can indeed be closed.
